# Generated by Django 5.0.4 on 2024-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_product_photo_alter_client_date_alter_order_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.AddField(
            model_name="product",
            name="photo_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
