# Generated by Django 5.0.4 on 2024-04-08 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_remove_product_photo_product_photo_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo_name",
        ),
        migrations.AddField(
            model_name="product",
            name="photo_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="date",
            field=models.DateField(default=datetime.date(2024, 4, 8)),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(default=datetime.date(2024, 4, 8)),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateField(default=datetime.date(2024, 4, 8)),
        ),
    ]
